# Generated by Django 2.0.2 on 2018-04-07 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileNameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('upload_time', models.DateTimeField(default=datetime.datetime.now)),
                ('file_obj', models.FileField(upload_to='stat_application/temp/files/')),
                ('session_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MethodModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_ja', models.CharField(max_length=50)),
                ('model_en', models.CharField(max_length=50)),
                ('upload_time', models.DateTimeField(default=datetime.datetime.now)),
                ('session_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SummaryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('upload_time', models.DateTimeField(default=datetime.datetime.now)),
                ('aic', models.FloatField(default=0)),
                ('bic', models.FloatField(default=0)),
                ('hqic', models.FloatField(default=0)),
                ('p', models.IntegerField(default=0)),
                ('d', models.IntegerField(default=0)),
                ('q', models.IntegerField(default=0)),
                ('sp', models.IntegerField(default=0)),
                ('sd', models.IntegerField(default=0)),
                ('sq', models.IntegerField(default=0)),
                ('rsq', models.FloatField(default=0)),
                ('rsq_adj', models.FloatField(default=0)),
                ('dw', models.FloatField(default=0)),
                ('holdout', models.IntegerField(default=0)),
                ('method', models.CharField(max_length=50)),
                ('session_id', models.CharField(max_length=50)),
            ],
        ),
    ]
