# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-16 07:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FileNameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('upload_time', models.DateTimeField(default=datetime.datetime.now)),
                ('file_obj', models.FileField(upload_to='upload_form/static/files/')),
            ],
        ),
        migrations.CreateModel(
            name='ImageURLModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url_name', models.URLField()),
                ('upload_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
