# Generated by Django 2.0.2 on 2018-04-07 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stat_application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filenamemodel',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='methodmodel',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='summarymodel',
            name='session_id',
        ),
    ]
