# Generated by Django 2.0.2 on 2018-04-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filenamemodel',
            name='file_obj',
            field=models.FileField(upload_to='temp/files/'),
        ),
    ]
