# Generated by Django 2.0.5 on 2018-07-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_application', '0002_auto_20180407_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarymodel',
            name='auc',
            field=models.FloatField(default=0),
        ),
    ]
