# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-03 18:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_application', '0002_auto_20180223_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('upload_time', models.DateTimeField(default=datetime.datetime.now)),
                ('file_obj', models.FileField(upload_to='statistical_processing/static/files/')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageURLModel',
        ),
    ]
