# Generated by Django 2.0.2 on 2018-04-03 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stat_application', '0002_auto_20180404_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filenamemodel',
            old_name='session_id',
            new_name='session',
        ),
    ]
