# Generated by Django 2.0.5 on 2018-07-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_application', '0003_summarymodel_auc'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarymodel',
            name='accuracy',
            field=models.FloatField(default=0),
        ),
    ]
