# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-06 14:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_application', '0005_auto_20180306_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarymodel',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
