# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-08 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_application', '0006_summarymodel_upload_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarymodel',
            name='d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summarymodel',
            name='p',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summarymodel',
            name='q',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summarymodel',
            name='sd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summarymodel',
            name='sp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summarymodel',
            name='sq',
            field=models.IntegerField(default=0),
        ),
    ]
