# Generated by Django 2.0.2 on 2018-04-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_application', '0006_auto_20180404_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='filenamemodel',
            name='session_id',
            field=models.CharField(default='DUMMY', max_length=50),
            preserve_default=False,
        ),
    ]
