# Generated by Django 2.0.2 on 2018-04-06 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stat_application', '0007_filenamemodel_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filenamemodel',
            old_name='session_id',
            new_name='test',
        ),
    ]
