# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-08 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_application', '0007_auto_20180309_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarymodel',
            name='model',
            field=models.CharField(default='DUMMY', max_length=50),
            preserve_default=False,
        ),
    ]
