# Generated by Django 2.0.2 on 2018-04-06 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stat_application', '0008_auto_20180407_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filenamemodel',
            name='test',
        ),
    ]
