# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-09 07:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_application', '0008_summarymodel_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('upload_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='ResultFileModel',
        ),
    ]
