# Generated by Django 2.0.2 on 2018-04-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_application', '0009_remove_filenamemodel_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='filenamemodel',
            name='a',
            field=models.IntegerField(default=0),
        ),
    ]
