# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-09 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_application', '0009_auto_20180309_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='methodmodel',
            old_name='model',
            new_name='model_en',
        ),
        migrations.AddField(
            model_name='methodmodel',
            name='model_ja',
            field=models.CharField(default='DUMMY', max_length=50),
            preserve_default=False,
        ),
    ]
