# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-22 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_application', '0011_progressmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarymodel',
            name='rsq',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='summarymodel',
            name='rsq_adj',
            field=models.FloatField(default=0),
        ),
    ]
