# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-22 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_application', '0012_auto_20180322_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarymodel',
            name='holdout',
            field=models.IntegerField(default=0),
        ),
    ]
