# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-22 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_application', '0013_summarymodel_holdout'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarymodel',
            name='dw',
            field=models.FloatField(default=0),
        ),
    ]
