# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-24 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_application', '0015_auto_20180325_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='summarymodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
