# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-24 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_application', '0016_auto_20180325_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodmodel',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
