# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-24 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stat_application', '0017_auto_20180325_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
