# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-25 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_application', '0021_auto_20180325_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='filenamemodel',
            name='session_id',
            field=models.CharField(default='DUMYY', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='methodmodel',
            name='session_id',
            field=models.CharField(default='DUMYY', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summarymodel',
            name='session_id',
            field=models.CharField(default='DUMMY', max_length=100),
            preserve_default=False,
        ),
    ]
