# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-26 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stat_application', '0022_auto_20180325_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filenamemodel',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='methodmodel',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='summarymodel',
            name='session_id',
        ),
    ]
