# Generated by Django 2.0.2 on 2018-03-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_application', '0023_auto_20180327_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='filenamemodel',
            name='session_id',
            field=models.CharField(default='DUMYY', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='methodmodel',
            name='session_id',
            field=models.CharField(default='DUMMY', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summarymodel',
            name='session_id',
            field=models.CharField(default='DUMMY', max_length=100),
            preserve_default=False,
        ),
    ]
