# Generated by Django 2.0.2 on 2018-04-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_application', '0024_auto_20180328_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filenamemodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
